import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import { Header } from '@/components/Header';

import './globals.css';

const mulish = Mulish({
  variable: '--font-mulish',
  subsets: ['cyrillic'],
});

export const metadata: Metadata = {
  title: 'Коуч в кармане',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} antialiased`}>
        <Header />
        <main className="w-full mt-[80px]">{children}</main>
      </body>
    </html>
  );
}
